import json
from collections.abc import Callable, Iterable
from dataclasses import dataclass
from pathlib import Path

from fileidentification.definitions.models import (
    LogMsg,
    LogTables,
    Mode,
    Policies,
    PoliciesFile,
    PolicyParams,
    SfInfo,
)
from fileidentification.definitions.settings import DEFAULTPOLICIES, FMT2EXT, FDMsg, PLMsg
from fileidentification.tasks.os_tasks import remove
from fileidentification.workspace import Workspace
from fileidentification.wrappers.ffmpeg import ffmpeg_media_info


def build_policies(
    puids: Iterable[str],
    default_policies: Policies,
    mode: Mode,
    *,
    blank: bool = False,
    extend: bool = False,
    existing: Policies | None = None,
) -> tuple[Policies, list[str]]:
    """
    Build the policy map for the encountered puids. Pure: no file I/O, no shared-state mutation.

    blank: one accept-by-default entry per puid (no default lookup).
    Otherwise each puid takes its default policy; puids without a default get an empty fallback policy
    (unless in strict mode, where they are dropped).
    extend: puids already present in `existing` keep their existing (hand-tuned) policy.
    remove_original mode is propagated onto every resulting policy.

    Returns (policies, blank_puids) where blank_puids are the puids that received an empty fallback policy.
    """
    policies: Policies = {}
    blank_puids: list[str] = []

    if blank:
        for puid in puids:
            policies[puid] = PolicyParams(format_name=FMT2EXT[puid]["name"], remove_original=mode.REMOVEORIGINAL)
        return policies, blank_puids

    for puid in puids:
        if puid in default_policies:
            policies[puid] = default_policies[puid]
        # no default for this filetype and not strict: add an empty (blank) policy
        if not mode.STRICT and puid not in default_policies:
            policies[puid] = PolicyParams(format_name=FMT2EXT[puid]["name"])
            blank_puids.append(puid)
        # extend: keep an already existing policy for this puid
        if extend and existing and puid in existing:
            policies[puid] = existing[puid]
            if puid in blank_puids:
                blank_puids.remove(puid)
        # propagate remove_original mode
        if puid in policies and mode.REMOVEORIGINAL:
            policies[puid].remove_original = mode.REMOVEORIGINAL

    return policies, blank_puids


class PolicyError(Exception):
    """An external policies.json is missing or invalid. The caller persists run state and exits."""


@dataclass
class PolicyResolution:
    """Outcome of resolving policies for a run: the policy map and the blank-fallback PUIDs (None if not generated)."""

    policies: Policies
    blank: list[str] | None = None


def read_policies(policies_path: Path) -> Policies:
    """Read and validate a policies.json. Raises PolicyError if the file is missing or invalid."""
    if not policies_path.is_file():
        raise PolicyError(f"{policies_path} not found")  # noqa: EM102, TRY003
    try:
        return PoliciesFile(**json.loads(policies_path.read_text())).policies
    except ValueError as e:
        raise PolicyError(str(e)) from e


def _write_policies(outpath: Path, policies: Policies, *, blank: bool, extend: bool, strict: bool) -> None:
    """Serialize a generated / extended policies map to outpath with a provenance comment."""
    comment = "autogenerated"
    if blank:
        comment += " blank policies"
    else:
        if extend:
            comment += f" updating from {outpath}"
        comment += f" using default policies {DEFAULTPOLICIES}"
        if strict:
            comment += " in strict mode"
    jsonfile = PoliciesFile(name=outpath, comment=comment, policies=policies)
    jsonfile.name.write_text(jsonfile.model_dump_json(indent=4, exclude_none=True))


def resolve_policies(
    puids: Iterable[str],
    poljson: Path,
    mode: Mode,
    *,
    policies_path: Path | None = None,
    blank: bool = False,
    extend: bool = False,
    emit: Callable[[str], None] = lambda _msg: None,
) -> PolicyResolution:
    """
    Resolve the policy map for a run and return it (no shared-state mutation).

    Picks one source: the default location (_policies.json) if present, an external file passed via
    policies_path, or a freshly generated map from the default policies (optionally blank). extend then merges
    the filetypes found in the folder onto the resolved map, keeping any hand-tuned entries. A generated or
    extended map is (re)written to poljson; reading an existing map does not write.

    emit receives human-readable progress messages (no-op by default). Raises PolicyError if an external
    policies file is missing or invalid.
    """
    # a policies.json at the default location and no external one passed -> read from there
    if not policies_path and poljson.is_file():
        policies_path = poljson

    # nothing to read (or blank requested) -> generate from the default policies
    if not policies_path or blank:
        emit("Generating policies")
        default_policies: Policies = {} if blank else read_policies(DEFAULTPOLICIES)
        policies, blank_puids = build_policies(puids, default_policies, mode, blank=blank)
        _write_policies(poljson, policies, blank=blank, extend=False, strict=mode.STRICT)
        resolution = PolicyResolution(policies, None if blank else blank_puids)
    # read the passed / default-location policies as-is
    else:
        emit(f"Loading policies from {policies_path}")
        resolution = PolicyResolution(read_policies(policies_path))

    # extend: add filetypes the resolved map is missing, keep the existing (hand-tuned) entries
    if extend:
        emit(f"Updating the filetypes in policies {poljson}")
        policies, blank_puids = build_policies(
            puids, read_policies(DEFAULTPOLICIES), mode, extend=True, existing=resolution.policies
        )
        _write_policies(poljson, policies, blank=False, extend=True, strict=mode.STRICT)
        resolution = PolicyResolution(policies, blank_puids)

    return resolution


def apply_policy(sfinfo: SfInfo, policies: Policies, ws: Workspace, log_tables: LogTables, strict: bool) -> None:
    """
    Decide what to do with the file based on its policy entry.
    Sets sfinfo.status.pending=True if the file needs conversion.
    In strict mode, files with no policy entry are moved to _REMOVED; otherwise they are skipped with a log entry.
    Files marked accepted=True are also checked for invalid A/V streams (fmt/199, fmt/569) and flagged for
    re-encoding if needed.
    """
    puid = sfinfo.processed_as
    if not puid:
        return
    if sfinfo.status.pending:
        return

    if puid not in policies:
        # in strict mode, move file
        if strict:
            sfinfo.processing_logs.append(LogMsg(name="filehandler", msg=f"{PLMsg.NOTINPOLICIES}"))
            remove(sfinfo, ws, log_tables)
            return
        # just flag it as skipped
        sfinfo.processing_logs.append(LogMsg(name="filehandler", msg=f"{PLMsg.SKIPPED}"))
        return

    # case where file needs to be converted
    if not policies[puid].accepted:
        sfinfo.status.pending = True
        return

    # check if mp4 / mkv has correct stream (i.e. h264 and aac)
    if puid in ["fmt/199", "fmt/569"] and _has_invalid_streams(sfinfo, puid, ws, log_tables):
        sfinfo.status.pending = True
        return


def _has_invalid_streams(sfinfo: SfInfo, puid: str, ws: Workspace, log_tables: LogTables) -> bool:
    """Return true if video and audio codec differ from archival standards"""
    streams = ffmpeg_media_info(ws.abs_path(sfinfo.filename))
    if not streams:
        # ffprobe read no streams for a file we meant to stream-check: record a warning for the end-of-phase report
        sfinfo.warnings.append(LogMsg(name="ffmpeg", msg="could not read streams for the a/v stream check"))
        log_tables.diagnostics_add(sfinfo, FDMsg.WARNING)
        return False
    if puid in ["fmt/569"]:
        # only the video codec has to be ffv1 -> return false as soon as any stream is ffv1
        return all(stream["codec_name"] not in ["ffv1"] for stream in streams)  # type: ignore[index]
    if puid in ["fmt/199"]:
        # video codec has to be h264, audio codec aac -> return true if any a/v stream does not match
        for stream in streams:
            if stream["codec_type"] not in ["video", "audio"]:  # type: ignore[index]
                continue
            if stream["codec_name"] not in ["h264", "aac"]:  # type: ignore[index]
                return True
    return False
