import json
from enum import StrEnum
from pathlib import Path

from pydantic import BaseModel, Field

# default policies
DEFAULTPOLICIES: Path = Path(__file__).parent / "default_policies.json"

# max number of files processed concurrently in inspect / assert_integrity / apply_policies / convert
MAX_WORKERS: int = 4
# max number of pygfried workers
PYG_WORKERS: int = 4

# paths tmp dir, logs
TMP_DIR = "__fileidentification"  # added to root folder
LOGJSON = "_log.json"
POLJSON = "_policies.json"
RMV_DIR = "_REMOVED"


# application settings
class DroidSigURL(StrEnum):
    """urls to fetch droid signature xml from national archives"""

    NALIST = "https://www.nationalarchives.gov.uk/aboutapps/pronom/droid-signature-files.htm"
    CDN = "https://cdn.nationalarchives.gov.uk/documents/DROID_SignatureFile_"


class FmtEntry(BaseModel):
    """One PUID entry in fmt_info.json: display name, known file extensions, and mimetype ('' if none)."""

    name: str = ""
    file_extensions: list[str] = Field(default_factory=list)
    mime: str = ""


# resolves a puid to its file format name, possible extensions and mimetype (regenerated by update.py)
FMTJSON: Path = Path(__file__).parent / "fmt_info.json"
FMT_INFO: dict[str, FmtEntry] = {
    puid: FmtEntry(**entry) for puid, entry in json.loads(FMTJSON.read_text()).items()
}


class Bin(StrEnum):
    MAGICK = "magick"
    FFMPEG = "ffmpeg"
    SOFFICE = "soffice"
    # INCSCAPE = "inkscape"
    EMPTY = ""


class LOPath(StrEnum):
    """path where LibreOffice exec is according to os"""

    Darwin = "/Applications/LibreOffice.app/Contents/MacOS/soffice"
    Linux = "libreoffice"


# it needs libreoffice v7.4 + for this to work, set to pdf/A version 2
PDFSETTINGS = ':writer_pdf_Export:{"SelectPdfVersion":{"type":"long","value":"2"}}'


CSVFIELDS = [
    "status",
    "filename",
    "filesize",
    "md5",
    "modified",
    "errors",
    "processed_as",
    "media_info",
    "processing_logs",
    "derived_from",
]


# msg


class PVErr(StrEnum):
    """policy validation errors"""

    SEMICOLON = "the char ';' is not an allowed in processing_args"
    MISS_CON = "missing 'target_container' in policy"
    MISS_EXP = "missing 'expected' in policy"
    MISS_BIN = "missing bin in policy"


class PLMsg(StrEnum):
    """policy log messages"""

    FALLBACK = "fmt not detected, fallback on extension"
    NOTINPOLICIES = "file format is not in policies and strict is set to true"
    SKIPPED = "file format is not in policies, skipped"


class LogLevel(StrEnum):
    """severity of a LogMsg entry"""

    INFO = "info"
    WARNING = "warning"
    ERROR = "error"


class FDMsg(StrEnum):
    """file diagnostic message"""

    EMPTYSOURCE = "empty source"
    ERROR = "file is corrupt"
    WARNING = "file has warnings"
    EXTMISMATCH = "extension mismatch"


class FPMsg(StrEnum):
    """file processing message"""

    PUIDFAIL = "failed to get fmt type"
    CONVFAILED = "conversion failed"
    NOTEXPECTEDFMT = "converted file does not match the expected fmt."


class REencMsg(StrEnum):
    """text in log for smaller errors that can be solved with re encoding the file"""

    ffmpeg1 = "A non-intra slice in an IDR NAL unit"


class ErrMsgIM(StrEnum):
    """
    Regex substrings in ImageMagick's stderr that indicate a file is not, or
    only partially, readable
    """

    cannot_read = r"can ?not read"
    directory_count = r"sanity check on directory count failed"
    read_directory = r"failed to read directory"
    insufficient_data = r"insufficient image data"
    premature_end = r"premature end of"
    unexpected_eof = r"unexpected end[- ]of[- ]file"
    short_read = r"expected \d+ bytes; found \d+ bytes"
    extra_content = r"extra content at the end of the document"
    parser_error = r"parser error"  # libxml2 (SVG) malformed markup
    read_exception = r"read exception"
    crc_error = r"crc error"
    corrupt_image = r"corrupt image"
    corrupt_jpeg = r"corrupt jpeg data"
    invalid_jpeg = r"invalid jpeg file structure|missing sos marker"
    improper_header = r"improper image header"
    unable_to_read = r"unable to (read|decode|open)"
    zero_size = r"negative or zero image size"
